# Day 3

## Advanced exercises
a. Given a list of XYZ-coordinates, p,

`[[1.0, 2.0, 10],
 [3.0, 4.0, 20],
 [5.0, 6.0, 30],
 [7.0, 8.0, 40]]`
 
 Normalise each coordinate by dividing with its Z (3rd) element. For example, the first row becomes:

`[1/10, 2/10, 10/10]` Hint: extract the last column into a variable z, and then change its dimensions so that p / z works.

In [7]:
import numpy as np

A = np.array([[1.0, 2.0, 10],
              [3.0, 4.0, 20],
              [5.0, 6.0, 30],
              [7.0, 8.0, 40]])

def div_by_3rd(x):
    y = x/x[2]
    return y
    
np.apply_along_axis(div_by_3rd, 1, A)

array([[0.1       , 0.2       , 1.        ],
       [0.15      , 0.2       , 1.        ],
       [0.16666667, 0.2       , 1.        ],
       [0.175     , 0.2       , 1.        ]])

b. Create a 3x3 ndarray. Use fancy indexing to slice out the diagonal elements.

In [15]:
B = np.random.randint(0, 10, 9).reshape(3, 3)
print(B)
[B[0, 0], B[1, 1], B[2, 2]]

[[9 2 2]
 [1 0 2]
 [1 3 2]]


[9, 0, 2]

c. Generate a 10 x 3 array of random numbers (all between 0 and 1). From each row, pick the number closest to 0.75. Make use of np.abs and np.argmax to find the column j which contains the closest element in each row.

In [30]:
C = np.random.uniform(0, 1, 30).reshape(10, 3)

def pick_val(x):
    absdiff = np.abs(x - 0.75) 
    ind = np.argmin(absdiff)
    return x[ind]

print(C)
np.apply_along_axis(pick_val, 1, C)

[[0.11907316 0.73383442 0.67982993]
 [0.27347034 0.89939427 0.72442437]
 [0.96085866 0.79424555 0.90584779]
 [0.17772389 0.53235227 0.61254281]
 [0.75601817 0.12856719 0.99790163]
 [0.17754103 0.71669792 0.21481004]
 [0.98703608 0.9038795  0.81472912]
 [0.7655972  0.33364872 0.04442053]
 [0.08576186 0.47668438 0.50652058]
 [0.75564014 0.19798743 0.9878139 ]]


array([0.73383442, 0.72442437, 0.79424555, 0.61254281, 0.75601817,
       0.71669792, 0.81472912, 0.7655972 , 0.50652058, 0.75564014])

d. Predict and verify the shape of the following slicing operation.

`x = np.empty((10, 8, 6))`

`idx0 = np.zeros((3, 8)).astype(int)
idx1 = np.zeros((3, 1)).astype(int)
idx2 = np.zeros((1, 1)).astype(int)`

`x[idx0, idx1, idx2]`

In [109]:
x = np.empty((10, 8, 6))

idx0 = np.zeros((3, 8)).astype(int)
idx1 = np.zeros((3, 1)).astype(int)
idx2 = np.zeros((1, 1)).astype(int)

x[idx0, idx1, idx2]

print(idx0.shape)
print(idx1.shape)
print(idx2.shape)

y = np.arange(0, 27).reshape(3, 3, 3)
y
#y[idx0, idx1, idx2]

(3, 8)
(3, 1)
(1, 1)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])